# OverlayAI - edita aqui o usa el menu (tecla configurable)
menu_title=Ianveig29 C.H.E.A.T
menu_key=45

show_teammates=1
show_names=1
visibility_names=1
visibility_boxes=1
show_hp_text=1
show_hp_bar=1
show_armor_bar=1
show_armor_text=1
show_debug=0
name_text_anchor=0

enemy_box=240,50,50
team_box=80,160,255
hp_text=255,255,255
name_text=255,255,255
name_visible=80,255,120
name_hidden=255,70,70
box_visible=80,255,120
box_hidden=255,70,70
armor_bar=70,140,255
